Feat/restrict resolver
acmutd/portal-next pull request #234
Opened 2024-02-12 04:56 UTC by MistahSanta

Created the resolver, but unsure if malware is working. Would love a second pair of eyes to look at

2024-02-14 03:18 UTC, DedsecKnight commented on lib/graphql/middlewares/only-owners.ts
> +    if ( !profile || profile.id !== session.id  ) {
I believe it should be `profile.userId !== session.id` instead of `profile.id !== session.id`.

2024-02-14 03:21 UTC, DedsecKnight commented on lib/graphql/resolvers/EventCheckin.resolver.ts
> +  @UseMiddleware([checkValidEvent, onlyOwners])
`args.where.userId` will be undefined for this query.

2024-02-14 03:22 UTC, DedsecKnight commented on lib/graphql/resolvers/OldEvent.resolver.ts
> +  @UseMiddleware( onlyOwners )
`args.where.userId` will also be undefined for this resolver.

2024-02-17 05:33 UTC, DedsecKnight requested changes

2024-02-17 05:33 UTC, DedsecKnight commented on lib/graphql/middlewares/only-profile-owner.ts
> +export const onlyProfileOwner: MiddlewareFn<TContext> = async( {args, context}, next) => {
Should `return next()` at the end of function.

2024-02-17 05:33 UTC, DedsecKnight commented on lib/graphql/middlewares/only-event-owner.ts
> +    return next;
`next()`

2024-02-17 05:58 UTC, MistahSanta commented on lib/graphql/middlewares/only-event-owner.ts
> +    return next;
good catch!

2024-02-17 06:06 UTC, DedsecKnight commented on lib/graphql/middlewares/only-event-owner.ts
> +    const owner_Profile = await context.prisma.profile.findFirst ({
Probably better to reject request if `owner_Profile` is null. 
nit: rewrite `owner_Profile` to `ownerProfile`

2024-02-17 06:06 UTC, DedsecKnight commented on lib/graphql/middlewares/only-profile-owner.ts
> +    const owner_Profile = await context.prisma.profile.findFirst({
^

2024-02-23 06:55 UTC, DedsecKnight approved these changes

2024-02-23 06:56 UTC, merged